// ═══════════════════════════════════════════════
// SELENE ACADEMIA — Constants & Data
// ═══════════════════════════════════════════════

// ── Design Tokens (complement Tailwind) ──
export const COLORS = {
  gold: '#C9A84C',
  teal: '#5B9E8F',
  blue: '#4A6FA5',
  purple: '#7B68AE',
  rose: '#C97B8B',
  success: '#5BB88F',
};

// ── Course Catalog ──
export const COURSES = [
  {
    id: 'brujula-interior',
    title: 'Despierta tu Brújula Interior',
    subtitle: 'Fundamentos de consciencia espiritual y autoconocimiento cósmico',
    level: 'Nivel 0',
    hours: '12h',
    modules: 6,
    lessons_count: 24,
    price: 0,
    price_label: 'GRATIS',
    stripe_price_id: null,
    icon: '🌟',
    color: COLORS.teal,
    tag: 'Lead Magnet',
    science: 'Neuroplasticidad (MBSR — Kabat-Zinn 1990), cronobiología introductoria, eje intestino-cerebro (Mayer 2011).',
    description: 'El punto de partida. Descubre que tienes un don dormido y aprende a despertarlo. Tu carta natal básica, tu primera meditación con resultados reales, y la hoja de ruta para tu camino formativo.',
    for_whom: 'Curiosos, escépticos, personas que sienten que "hay algo más" pero no saben por dónde empezar.',
    outcome: 'Entiendes tu carta natal básica, has hecho tu primera meditación con resultados, y sabes qué camino formativo seguir.',
    lessons: [
      { id: 'b1-l1', title: 'Qué es una carta natal (y qué NO es)', duration: '35 min', type: 'lesson', module: 1, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l1.mp4' },
      { id: 'b1-l2', title: 'No es fe ciega: es atención entrenada', duration: '35 min', type: 'lesson', module: 1, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l2.mp4' },
      { id: 'b1-l3', title: 'Tu cerebro como antena: neuroplasticidad', duration: '40 min', type: 'lesson', module: 1, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l3.mp4' },
      { id: 'b1-q1', title: 'Quiz: Fundamentos de consciencia', duration: '8 min', type: 'quiz', module: 1 },
      { id: 'b1-l4', title: 'Tu mapa cósmico — La carta natal', duration: '40 min', type: 'lesson', module: 2, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l4.mp4' },
      { id: 'b1-l5', title: 'Sol, Luna, Ascendente: tu triángulo esencial', duration: '40 min', type: 'lesson', module: 2, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l5.mp4' },
      { id: 'b1-l6', title: 'Cronobiología: tu estación de nacimiento importa', duration: '35 min', type: 'lesson', module: 2, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l6.mp4' },
      { id: 'b1-q2', title: 'Quiz: Tu mapa cósmico', duration: '8 min', type: 'quiz', module: 2 },
      { id: 'b1-l7', title: 'Meditación y cerebro: la ciencia real', duration: '40 min', type: 'lesson', module: 3, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l7.mp4' },
      { id: 'b1-l8', title: 'MBSR: el protocolo con más evidencia', duration: '35 min', type: 'lesson', module: 3, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l8.mp4' },
      { id: 'b1-l9', title: 'Práctica guiada: tu primera meditación', duration: '40 min', type: 'lesson', module: 3, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l9.mp4' },
      { id: 'b1-q3', title: 'Quiz: Meditación basada en evidencia', duration: '8 min', type: 'quiz', module: 3 },
      { id: 'b1-l10', title: 'El péndulo interno: intuición vs. ego', duration: '35 min', type: 'lesson', module: 4, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l10.mp4' },
      { id: 'b1-l11', title: 'Señales del cuerpo: el eje intestino-cerebro', duration: '40 min', type: 'lesson', module: 4, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l11.mp4' },
      { id: 'b1-l12', title: 'Práctica: escucha tu intuición 7 días', duration: '35 min', type: 'lesson', module: 4, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l12.mp4' },
      { id: 'b1-q4', title: 'Quiz: Intuición entrenada', duration: '8 min', type: 'quiz', module: 4 },
      { id: 'b1-l13', title: 'Los 4 pilares del autoconocimiento', duration: '40 min', type: 'lesson', module: 5, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l13.mp4' },
      { id: 'b1-l14', title: 'Tu perfil energético: descúbrelo', duration: '40 min', type: 'lesson', module: 5, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l14.mp4' },
      { id: 'b1-l15', title: 'Práctica: mapa de energía personal', duration: '35 min', type: 'lesson', module: 5, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l15.mp4' },
      { id: 'b1-q5', title: 'Quiz: Autoconocimiento', duration: '8 min', type: 'quiz', module: 5 },
      { id: 'b1-l16', title: 'Tu hoja de ruta formativa', duration: '35 min', type: 'lesson', module: 6, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l16.mp4' },
      { id: 'b1-l17', title: 'Resumen: lo que has aprendido', duration: '30 min', type: 'lesson', module: 6, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l17.mp4' },
      { id: 'b1-l18', title: 'Recursos y próximos pasos', duration: '25 min', type: 'lesson', module: 6, videoUrl: 'https://lerfefvqfwdsubchzqyk.supabase.co/storage/v1/object/public/course-videos/brujula-interior/m1_l18.mp4' },
      { id: 'b1-exam', title: 'Evaluación final + Certificado', duration: '20 min', type: 'exam', module: 6 },
    ],
  },
  {
    id: 'magnetismo-consciente',
    title: 'Magnetismo Consciente',
    subtitle: 'Neurociencia de la atracción y la intención — lo que la ley de atracción no te cuenta',
    level: 'Nivel 1',
    hours: '18h',
    modules: 8,
    lessons_count: 24,
    price: 2499,
    price_label: '€24,99',
    stripe_price_id: 'price_1TCyZs3w6LxSJCcMfKHSHQsA',
    icon: '🧲',
    color: COLORS.purple,
    tag: 'Popular',
    science: 'HeartMath Institute (McCraty 2015), neuroplasticidad (Lazar 2005), epigenética conductual (Meaney 2001), sistema de activación reticular.',
    description: 'La "ley de atracción" con base científica real. Coherencia cardíaca, rewiring neuronal, y cómo tus genes responden a tus estados emocionales.',
    for_whom: 'Personas interesadas en manifestación que quieren entender QUÉ funciona y POR QUÉ, sin pseudociencia.',
    outcome: 'Dominas la coherencia cardíaca HeartMath, entiendes la neuroplasticidad aplicada, y tienes una rutina de 21 días con base científica.',
    lessons: [
      { id: 'mc-l1', title: 'La ley de atracción bajo el microscopio', duration: '16 min', type: 'lesson', module: 1 },
      { id: 'mc-l2', title: 'Qué dice la ciencia sobre la intención', duration: '18 min', type: 'lesson', module: 1 },
      { id: 'mc-l3', title: 'El sistema de activación reticular: tu filtro interno', duration: '15 min', type: 'lesson', module: 1 },
      { id: 'mc-q1', title: 'Quiz: Fundamentos de la atracción consciente', duration: '5 min', type: 'quiz', module: 1 },
      { id: 'mc-l4', title: 'Coherencia cardíaca: el corazón como generador', duration: '20 min', type: 'lesson', module: 2 },
      { id: 'mc-l5', title: 'Protocolo HeartMath: práctica guiada', duration: '18 min', type: 'lesson', module: 2 },
      { id: 'mc-l6', title: 'Variabilidad cardíaca y estados emocionales', duration: '14 min', type: 'lesson', module: 2 },
      { id: 'mc-q2', title: 'Quiz: Coherencia cardíaca', duration: '5 min', type: 'quiz', module: 2 },
      { id: 'mc-l7', title: 'Neuroplasticidad: tu cerebro se recablea', duration: '18 min', type: 'lesson', module: 3 },
      { id: 'mc-l8', title: 'Visualización y corteza motora: ver es activar', duration: '16 min', type: 'lesson', module: 3 },
      { id: 'mc-l9', title: 'Práctica: rewiring en 10 minutos diarios', duration: '12 min', type: 'lesson', module: 3 },
      { id: 'mc-q3', title: 'Quiz: Neuroplasticidad aplicada', duration: '5 min', type: 'quiz', module: 3 },
      { id: 'mc-l10', title: 'Epigenética: tus emociones hablan a tus genes', duration: '20 min', type: 'lesson', module: 4 },
      { id: 'mc-l11', title: 'Estrés crónico vs. estados elevados', duration: '15 min', type: 'lesson', module: 4 },
      { id: 'mc-l12', title: 'Meditación y expresión génica: los estudios', duration: '16 min', type: 'lesson', module: 4 },
      { id: 'mc-q4', title: 'Quiz: Epigenética conductual', duration: '5 min', type: 'quiz', module: 4 },
      { id: 'mc-l13', title: 'El efecto placebo como prueba del magnetismo', duration: '18 min', type: 'lesson', module: 5 },
      { id: 'mc-l14', title: 'Expectativas y profecías autocumplidas', duration: '14 min', type: 'lesson', module: 5 },
      { id: 'mc-l15', title: 'Sesgo de confirmación: aliado o enemigo', duration: '15 min', type: 'lesson', module: 5 },
      { id: 'mc-q5', title: 'Quiz: Psicología de la manifestación', duration: '5 min', type: 'quiz', module: 5 },
      { id: 'mc-l16', title: 'Tu protocolo de 21 días: diseño personalizado', duration: '20 min', type: 'lesson', module: 6 },
      { id: 'mc-l17', title: 'Magnetismo y carta natal: tu estilo de intención', duration: '16 min', type: 'lesson', module: 6 },
      { id: 'mc-l18', title: 'Integración final: tu rutina magnética diaria', duration: '12 min', type: 'lesson', module: 6 },
      { id: 'mc-exam', title: 'Evaluación final', duration: '10 min', type: 'exam', module: 6 },
    ],
  },
  {
    id: 'astrologia-natal',
    title: 'Astrología Natal Profunda',
    subtitle: 'Tu carta natal al detalle — planetas, casas, aspectos y tránsitos',
    level: 'Nivel 1',
    hours: '22h',
    modules: 10,
    lessons_count: 30,
    price: 2999,
    price_label: '€29,99',
    stripe_price_id: 'price_1TCyZt3w6LxSJCcM0ht4G5O5',
    icon: '🌙',
    color: COLORS.blue,
    tag: 'Nuevo',
    science: 'Astronomía posicional (efemérides JPL), cronobiología (Foster & Kreitzman 2017), psicología junguiana (arquetipos).',
    description: 'De saber tu signo solar a interpretar una carta natal completa. Planetas personales, casas, aspectos, y cómo leer los tránsitos actuales.',
    for_whom: 'Quienes quieren ir más allá del horóscopo del periódico y entender la astrología como sistema simbólico complejo.',
    outcome: 'Interpretas tu carta natal completa, identificas tus tránsitos activos, y puedes hacer una lectura básica para otros.',
    lessons: [
      { id: 'an-l1', title: 'Los 10 planetas: el elenco de tu psique', duration: '20 min', type: 'lesson', module: 1 },
      { id: 'an-l2', title: 'Sol y Luna: identidad y emociones', duration: '18 min', type: 'lesson', module: 1 },
      { id: 'an-l3', title: 'Mercurio, Venus, Marte: comunicación, amor, acción', duration: '16 min', type: 'lesson', module: 1 },
      { id: 'an-q1', title: 'Quiz: Planetas personales', duration: '5 min', type: 'quiz', module: 1 },
      { id: 'an-l4', title: 'Júpiter y Saturno: expansión y estructura', duration: '18 min', type: 'lesson', module: 2 },
      { id: 'an-l5', title: 'Urano, Neptuno, Plutón: transformación generacional', duration: '20 min', type: 'lesson', module: 2 },
      { id: 'an-l6', title: 'Los Nodos Lunares: el eje de propósito', duration: '16 min', type: 'lesson', module: 2 },
      { id: 'an-q2', title: 'Quiz: Planetas sociales y transpersonales', duration: '5 min', type: 'quiz', module: 2 },
      { id: 'an-l7', title: 'Las 12 casas: las áreas de tu vida', duration: '22 min', type: 'lesson', module: 3 },
      { id: 'an-l8', title: 'Casas angulares (1, 4, 7, 10): los pilares', duration: '18 min', type: 'lesson', module: 3 },
      { id: 'an-l9', title: 'Casas sucedentes y cadentes: recursos y adaptación', duration: '16 min', type: 'lesson', module: 3 },
      { id: 'an-q3', title: 'Quiz: Las 12 casas', duration: '5 min', type: 'quiz', module: 3 },
      { id: 'an-l10', title: 'Los 12 signos como arquetipos psicológicos', duration: '20 min', type: 'lesson', module: 4 },
      { id: 'an-l11', title: 'Elementos y modalidades: fuego, tierra, aire, agua', duration: '16 min', type: 'lesson', module: 4 },
      { id: 'an-l12', title: 'El Ascendente: tu máscara y tu puerta al mundo', duration: '18 min', type: 'lesson', module: 4 },
      { id: 'an-q4', title: 'Quiz: Signos y Ascendente', duration: '5 min', type: 'quiz', module: 4 },
      { id: 'an-l13', title: 'Aspectos: conjunción, oposición, trígono, cuadratura', duration: '22 min', type: 'lesson', module: 5 },
      { id: 'an-l14', title: 'Aspectos menores y patrones de aspecto', duration: '18 min', type: 'lesson', module: 5 },
      { id: 'an-l15', title: 'Práctica: lee los aspectos de tu propia carta', duration: '20 min', type: 'lesson', module: 5 },
      { id: 'an-q5', title: 'Quiz: Aspectos planetarios', duration: '5 min', type: 'quiz', module: 5 },
      { id: 'an-l16', title: 'Tránsitos: cuando el cielo activa tu carta', duration: '20 min', type: 'lesson', module: 6 },
      { id: 'an-l17', title: 'Retorno de Saturno y otros ciclos clave', duration: '18 min', type: 'lesson', module: 6 },
      { id: 'an-l18', title: 'Práctica: identifica tus tránsitos activos ahora', duration: '15 min', type: 'lesson', module: 6 },
      { id: 'an-q6', title: 'Quiz: Tránsitos', duration: '5 min', type: 'quiz', module: 6 },
      { id: 'an-l19', title: 'Lectura integrada: unir planetas, casas, signos y aspectos', duration: '22 min', type: 'lesson', module: 7 },
      { id: 'an-l20', title: 'Práctica: lectura completa de tu carta natal', duration: '25 min', type: 'lesson', module: 7 },
      { id: 'an-l21', title: 'Cómo hacer una lectura para otra persona', duration: '18 min', type: 'lesson', module: 7 },
      { id: 'an-q7', title: 'Quiz: Lectura integrada', duration: '5 min', type: 'quiz', module: 7 },
      { id: 'an-l22', title: 'Recursos, herramientas y próximos pasos', duration: '12 min', type: 'lesson', module: 7 },
      { id: 'an-exam', title: 'Evaluación final', duration: '15 min', type: 'exam', module: 7 },
    ],
  },
  {
    id: 'cronobiologia',
    title: 'Cronobiología y Ritmos Vitales',
    subtitle: 'La ciencia real de cómo los ciclos cósmicos afectan tu biología',
    level: 'Nivel 2',
    hours: '20h',
    modules: 8,
    lessons_count: 24,
    price: 2999,
    price_label: '€29,99',
    stripe_price_id: 'price_1TCyZu3w6LxSJCcM1Weo76QI',
    icon: '🧬',
    color: COLORS.teal,
    tag: 'Ciencia',
    science: 'Ritmos circadianos (Nobel 2017 — Hall, Rosbash, Young), genes PER1/CLOCK, melatonina, cortisol, serotonina, estudios Gonda 2014, Current Biology 2013/2021.',
    description: 'El curso más "científico" de Selene. Donde la astrología encuentra la biología molecular. Ritmos circadianos, ultradianos, lunares y estacionales con evidencia real.',
    for_whom: 'Escépticos curiosos, profesionales de salud/bienestar, y cualquiera que quiera entender la base real.',
    outcome: 'Entiendes cómo los ritmos biológicos afectan tu vida diaria y diseñas tu calendario personalizado en sincronía.',
    lessons: [
      { id: 'cb-l1', title: 'Qué es la cronobiología (y por qué ganó el Nobel)', duration: '18 min', type: 'lesson', module: 1 },
      { id: 'cb-l2', title: 'El reloj maestro: núcleo supraquiasmático', duration: '16 min', type: 'lesson', module: 1 },
      { id: 'cb-l3', title: 'Genes reloj: PER, CLOCK, CRY y tu ADN temporal', duration: '20 min', type: 'lesson', module: 1 },
      { id: 'cb-q1', title: 'Quiz: Fundamentos de cronobiología', duration: '5 min', type: 'quiz', module: 1 },
      { id: 'cb-l4', title: 'Ritmos circadianos: las 24 horas de tu cuerpo', duration: '20 min', type: 'lesson', module: 2 },
      { id: 'cb-l5', title: 'Cronotipos: alondra, búho y colibrí', duration: '16 min', type: 'lesson', module: 2 },
      { id: 'cb-l6', title: 'Melatonina, cortisol, serotonina: tus hormonas rítmicas', duration: '18 min', type: 'lesson', module: 2 },
      { id: 'cb-q2', title: 'Quiz: Ritmos circadianos', duration: '5 min', type: 'quiz', module: 2 },
      { id: 'cb-l7', title: 'Ritmos ultradianos: los ciclos de 90 minutos', duration: '14 min', type: 'lesson', module: 3 },
      { id: 'cb-l8', title: 'El ciclo menstrual como reloj biológico', duration: '18 min', type: 'lesson', module: 3 },
      { id: 'cb-l9', title: 'Ritmos infradianos: estaciones y nacimiento', duration: '16 min', type: 'lesson', module: 3 },
      { id: 'cb-q3', title: 'Quiz: Ritmos ultra e infradianos', duration: '5 min', type: 'quiz', module: 3 },
      { id: 'cb-l10', title: 'La Luna y la biología: lo que dicen los estudios', duration: '20 min', type: 'lesson', module: 4 },
      { id: 'cb-l11', title: 'Sueño, ciclo lunar y ritmos cerebrales', duration: '16 min', type: 'lesson', module: 4 },
      { id: 'cb-l12', title: 'Estaciones de nacimiento y temperamento: los datos', duration: '18 min', type: 'lesson', module: 4 },
      { id: 'cb-q4', title: 'Quiz: Luna, estaciones y biología', duration: '5 min', type: 'quiz', module: 4 },
      { id: 'cb-l13', title: 'Jet lag social: vivir contra tu reloj interno', duration: '16 min', type: 'lesson', module: 5 },
      { id: 'cb-l14', title: 'Luz artificial y disrupción circadiana', duration: '14 min', type: 'lesson', module: 5 },
      { id: 'cb-l15', title: 'Cronomedicina: tratar según la hora del día', duration: '18 min', type: 'lesson', module: 5 },
      { id: 'cb-q5', title: 'Quiz: Disrupción y cronomedicina', duration: '5 min', type: 'quiz', module: 5 },
      { id: 'cb-l16', title: 'Tu cronotipo personalizado: test y análisis', duration: '20 min', type: 'lesson', module: 6 },
      { id: 'cb-l17', title: 'Diseña tu calendario vital sincronizado', duration: '18 min', type: 'lesson', module: 6 },
      { id: 'cb-l18', title: 'Integración: cronobiología + carta natal', duration: '15 min', type: 'lesson', module: 6 },
      { id: 'cb-exam', title: 'Evaluación final', duration: '10 min', type: 'exam', module: 6 },
    ],
  },
  {
    id: 'tarot-intuitivo',
    title: 'Certificación en Tarot Intuitivo',
    subtitle: 'Conviértete en tarotista profesional — enfoque junguiano con base científica',
    level: 'Nivel 2',
    hours: '25h',
    modules: 8,
    lessons_count: 24,
    price: 6999,
    price_label: '€69,99',
    stripe_price_id: 'price_1TEqZk3w6LxSJCcMixG3Lv1H',
    icon: '✨',
    color: COLORS.gold,
    tag: '🎓 Certificación',
    certification: true,
    cert_requirements: '7 quizzes aprobados + examen final (≥70%) + 5 tiradas supervisadas',
    cert_badge: 'Tarotista Certificado/a Selene',
    cert_directory: true,
    science: 'Psicología proyectiva (Semetsky 2006), arquetipos del inconsciente colectivo (Jung 1964), intuición como heurístico experto (Gigerenzer 2007, Kahneman 2011), marcadores somáticos (Bechara & Damasio 1997).',
    description: 'No memorices significados — aprende a SENTIR las cartas. Tarot como técnica proyectiva con base en psicología junguiana. 24 lecciones con casos prácticos, ejercicios guiados y módulo de negocio.',
    for_whom: 'Quienes quieren ejercer profesionalmente como tarotistas con un enfoque terapéutico y proyectivo, respaldado por psicología junguiana.',
    outcome: 'Realizas tiradas profesionales de 30+ min, integras tarot + astrología, sabes cobrar (€40-150/sesión), y tienes certificado verificable.',
    lessons: [
      { id: 'ti-l1', title: 'Qué es el tarot (y qué NO es)', duration: '40 min', type: 'lesson', module: 1 },
      { id: 'ti-l2', title: 'Del juego de cartas al espejo psicológico', duration: '35 min', type: 'lesson', module: 1 },
      { id: 'ti-l3', title: 'Tu baraja: elegir, conectar, preparar', duration: '35 min', type: 'lesson', module: 1 },
      { id: 'ti-q1', title: 'Quiz: Fundamentos del tarot', duration: '8 min', type: 'quiz', module: 1 },
      { id: 'ti-l4', title: 'El Loco, El Mago, La Sacerdotisa (0-II)', duration: '45 min', type: 'lesson', module: 2 },
      { id: 'ti-l5', title: 'La Emperatriz, El Emperador, El Hierofante (III-V)', duration: '45 min', type: 'lesson', module: 2 },
      { id: 'ti-l6', title: 'Los Enamorados → La Rueda (VI-X)', duration: '45 min', type: 'lesson', module: 2 },
      { id: 'ti-q2', title: 'Quiz: Arcanos Mayores I', duration: '8 min', type: 'quiz', module: 2 },
      { id: 'ti-l7', title: 'La Fuerza, El Colgado, La Muerte, Templanza (XI-XIV)', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'ti-l8', title: 'El Diablo, La Torre, La Estrella, La Luna (XV-XVIII)', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'ti-l9', title: 'El Sol, El Juicio, El Mundo + El viaje completo (XIX-XXI)', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'ti-q3', title: 'Quiz: Arcanos Mayores II', duration: '8 min', type: 'quiz', module: 3 },
      { id: 'ti-l10', title: 'Los 4 palos: fuego, agua, aire, tierra', duration: '40 min', type: 'lesson', module: 4 },
      { id: 'ti-l11', title: 'Numerología del 1 al 10: el ciclo en cada palo', duration: '40 min', type: 'lesson', module: 4 },
      { id: 'ti-l12', title: 'Figuras de corte: Paje, Caballero, Reina, Rey', duration: '40 min', type: 'lesson', module: 4 },
      { id: 'ti-q4', title: 'Quiz: Arcanos Menores', duration: '8 min', type: 'quiz', module: 4 },
      { id: 'ti-l13', title: 'Intuición vs memorización: por qué necesitas ambas', duration: '40 min', type: 'lesson', module: 5 },
      { id: 'ti-l14', title: 'Marcadores somáticos: tu cuerpo como brújula', duration: '40 min', type: 'lesson', module: 5 },
      { id: 'ti-l15', title: 'Lectura libre: sin libro, solo imagen y sensación', duration: '35 min', type: 'lesson', module: 5 },
      { id: 'ti-q5', title: 'Quiz: Lectura intuitiva', duration: '8 min', type: 'quiz', module: 5 },
      { id: 'ti-l16', title: 'Tirada de 1 carta: la práctica diaria', duration: '35 min', type: 'lesson', module: 6 },
      { id: 'ti-l17', title: 'Tiradas de 3 y 5 cartas', duration: '40 min', type: 'lesson', module: 6 },
      { id: 'ti-l18', title: 'Cruz Celta y tiradas propias', duration: '45 min', type: 'lesson', module: 6 },
      { id: 'ti-q6', title: 'Quiz: Tiradas', duration: '8 min', type: 'quiz', module: 6 },
      { id: 'ti-l19', title: 'Leer para otra persona: la sesión completa', duration: '40 min', type: 'lesson', module: 7 },
      { id: 'ti-l20', title: 'Ética del tarotista: lo que NUNCA debes decir', duration: '35 min', type: 'lesson', module: 7 },
      { id: 'ti-l21', title: 'Comunicar insights difíciles con empatía', duration: '40 min', type: 'lesson', module: 7 },
      { id: 'ti-q7', title: 'Quiz: Práctica profesional', duration: '8 min', type: 'quiz', module: 7 },
      { id: 'ti-l22', title: 'Cuánto cobrar: datos reales del mercado', duration: '35 min', type: 'lesson', module: 8 },
      { id: 'ti-l23', title: 'Tu presencia online y primeros clientes', duration: '35 min', type: 'lesson', module: 8 },
      { id: 'ti-l24', title: 'Combinaciones rentables y próximos pasos', duration: '30 min', type: 'lesson', module: 8 },
      { id: 'ti-exam', title: 'Evaluación final + Certificado', duration: '25 min', type: 'exam', module: 8 },
    ],
  },
  {
    id: 'raices-invisibles',
    title: 'Certificación en Astrogenealogía',
    subtitle: 'Raíces Invisibles — descubre y transforma los patrones familiares ocultos en tu carta natal',
    level: 'Nivel 2',
    hours: '20h',
    modules: 8,
    lessons_count: 24,
    price: 6999,
    price_label: '€69,99',
    stripe_price_id: 'price_1TEqa53w6LxSJCcMLNAq7nqB',
    icon: '🌿',
    color: COLORS.rose,
    tag: '🎓 Certificación',
    certification: true,
    cert_requirements: '8 quizzes aprobados + examen teórico (≥70%) + genograma familiar + lectura sistémica de carta natal',
    cert_badge: 'Astrogeneáloga Certificada Selene',
    cert_directory: true,
    science: 'Teoría de Sistemas Familiares de Bowen, epigenética transgeneracional (Yehuda 2016), teoría del apego (Bowlby 1969), IFS (Schwartz 1995), astronomía posicional (Casas 4, 8, 12).',
    description: 'Tu carta natal guarda las huellas de tu sistema familiar. Aprende a leer los patrones heredados en las Casas 4, 8 y 12, la Luna, Saturno y los Nodos Lunares — y a transformarlos con ejercicios sistémicos basados en evidencia.',
    for_whom: 'Personas que sienten que repiten patrones familiares, que quieren entender la herencia emocional invisible, o que buscan sanar dinámicas con su familia de origen.',
    outcome: 'Identificas los patrones transgeneracionales en tu carta natal, comprendes las dinámicas sistémicas de tu familia, y tienes herramientas concretas para transformar lealtades invisibles.',
    lessons: [
      // Module 1: Fundamentos sistémicos
      { id: 'ri-l1', title: '¿Qué son los patrones familiares invisibles?', duration: '16 min', type: 'lesson', module: 1 },
      { id: 'ri-l2', title: 'Teoría de Sistemas Familiares: de Bowen a la epigenética', duration: '18 min', type: 'lesson', module: 1 },
      { id: 'ri-l3', title: 'Las tres leyes sistémicas: pertenencia, orden y equilibrio', duration: '15 min', type: 'lesson', module: 1 },
      { id: 'ri-q1', title: 'Quiz: Fundamentos sistémicos', duration: '5 min', type: 'quiz', module: 1 },
      // Module 2: La carta natal como mapa familiar
      { id: 'ri-l4', title: 'Casa 4: tus raíces, tu hogar emocional', duration: '20 min', type: 'lesson', module: 2 },
      { id: 'ri-l5', title: 'Casa 8: herencias, transformación y secretos familiares', duration: '18 min', type: 'lesson', module: 2 },
      { id: 'ri-l6', title: 'Casa 12: el inconsciente colectivo familiar', duration: '17 min', type: 'lesson', module: 2 },
      { id: 'ri-q2', title: 'Quiz: Las casas familiares', duration: '5 min', type: 'quiz', module: 2 },
      // Module 3: Planetas de herencia
      { id: 'ri-l7', title: 'La Luna: tu herencia emocional materna', duration: '18 min', type: 'lesson', module: 3 },
      { id: 'ri-l8', title: 'Saturno: mandatos, límites y estructura heredada', duration: '16 min', type: 'lesson', module: 3 },
      { id: 'ri-l9', title: 'Los Nodos Lunares: karma generacional', duration: '20 min', type: 'lesson', module: 3 },
      { id: 'ri-q3', title: 'Quiz: Planetas de herencia', duration: '5 min', type: 'quiz', module: 3 },
      // Module 4: Epigenética y trauma transgeneracional
      { id: 'ri-l10', title: 'Epigenética: cómo el trauma se hereda biológicamente', duration: '18 min', type: 'lesson', module: 4 },
      { id: 'ri-l11', title: 'Lealtades invisibles: por qué repites lo que no viviste', duration: '15 min', type: 'lesson', module: 4 },
      { id: 'ri-l12', title: 'Ejercicio: tu genograma emocional', duration: '22 min', type: 'lesson', module: 4 },
      { id: 'ri-q4', title: 'Quiz: Herencia transgeneracional', duration: '5 min', type: 'quiz', module: 4 },
      // Module 5: Constelaciones y carta natal
      { id: 'ri-l13', title: 'Astrogenealogía: cuando la carta natal habla de tu familia', duration: '20 min', type: 'lesson', module: 5 },
      { id: 'ri-l14', title: 'Aspectos planetarios que revelan dinámicas familiares', duration: '18 min', type: 'lesson', module: 5 },
      { id: 'ri-l15', title: 'Práctica: lectura sistémica de tu propia carta', duration: '25 min', type: 'lesson', module: 5 },
      { id: 'ri-q5', title: 'Quiz: Astrogenealogía aplicada', duration: '5 min', type: 'quiz', module: 5 },
      // Module 6: Ejercicios de transformación
      { id: 'ri-l16', title: 'Movimientos sistémicos: ejercicios individuales guiados', duration: '22 min', type: 'lesson', module: 6 },
      { id: 'ri-l17', title: 'Ritual de reconexión: honrar tu linaje', duration: '18 min', type: 'lesson', module: 6 },
      { id: 'ri-l18', title: 'Práctica: carta de liberación a tu sistema familiar', duration: '20 min', type: 'lesson', module: 6 },
      { id: 'ri-q6', title: 'Quiz: Transformación sistémica', duration: '5 min', type: 'quiz', module: 6 },
      // Module 7: Relaciones y sistema actual
      { id: 'ri-l19', title: 'Cómo tus patrones familiares afectan tus relaciones', duration: '18 min', type: 'lesson', module: 7 },
      { id: 'ri-l20', title: 'Sinastría sistémica: tu pareja como espejo familiar', duration: '20 min', type: 'lesson', module: 7 },
      { id: 'ri-l21', title: 'Romper el ciclo: crear tu propio orden', duration: '16 min', type: 'lesson', module: 7 },
      { id: 'ri-q7', title: 'Quiz: Relaciones y sistema', duration: '5 min', type: 'quiz', module: 7 },
      // Module 8: Integración
      { id: 'ri-l22', title: 'Tu mapa completo: integrando carta natal + sistema familiar', duration: '22 min', type: 'lesson', module: 8 },
      { id: 'ri-l23', title: 'Plan de sanación sistémica personalizado', duration: '15 min', type: 'lesson', module: 8 },
      { id: 'ri-l24', title: 'Recursos, comunidad y próximos pasos', duration: '10 min', type: 'lesson', module: 8 },
      { id: 'ri-exam', title: 'Evaluación final + Certificado', duration: '15 min', type: 'exam', module: 8 },
    ],
  },
  {
    id: 'suenos-certificacion',
    title: 'Certificación en Interpretación de Sueños',
    subtitle: 'Jung + neurociencia del sueño — aprende a descifrar el lenguaje del inconsciente',
    level: 'Nivel 2',
    hours: '18h',
    modules: 8,
    lessons_count: 24,
    price: 4999,
    price_label: '€49,99',
    stripe_price_id: 'price_1TEqZY3w6LxSJCcMfQr60dWR',
    icon: '💤',
    color: COLORS.blue,
    tag: '🎓 Certificación',
    certification: true,
    cert_requirements: '6 quizzes aprobados + examen teórico (≥70%) + diario de sueños 30 días + interpretación final',
    cert_badge: 'Intérprete de Sueños Certificada Selene',
    cert_directory: true,
    science: 'Psicología analítica (Jung 1964), neurociencia del sueño (Walker 2017), simbología arquetípica, REM y consolidación de memoria.',
    description: 'No es un diccionario de sueños — es aprender a interpretar. Programa completo con diario guiado de 30 días, análisis junguiano, y la neurociencia que explica por qué soñamos lo que soñamos.',
    for_whom: 'Quienes quieren comprender sus sueños a nivel profundo y ofrecer interpretaciones profesionales con base psicológica y científica.',
    outcome: 'Interpretas sueños con método junguiano, llevas un diario estructurado, tienes certificado verificable y perfil en directorio Selene.',
    lessons: [
      { id: 'su-l1', title: '¿Por qué soñamos? La neurociencia del sueño', duration: '16 min', type: 'lesson', module: 1 },
      { id: 'su-l2', title: 'Fases del sueño: REM, consolidación y creatividad', duration: '14 min', type: 'lesson', module: 1 },
      { id: 'su-l3', title: 'Jung y el inconsciente: la función de los sueños', duration: '18 min', type: 'lesson', module: 1 },
      { id: 'su-q1', title: 'Quiz: Fundamentos del sueño', duration: '5 min', type: 'quiz', module: 1 },
      { id: 'su-l4', title: 'Arquetipos: los personajes universales de tus sueños', duration: '20 min', type: 'lesson', module: 2 },
      { id: 'su-l5', title: 'Símbolos: agua, fuego, animales, muerte', duration: '18 min', type: 'lesson', module: 2 },
      { id: 'su-l6', title: 'El contexto importa: mismo símbolo, distinto significado', duration: '15 min', type: 'lesson', module: 2 },
      { id: 'su-q2', title: 'Quiz: Simbología onírica', duration: '5 min', type: 'quiz', module: 2 },
      { id: 'su-l7', title: 'Cómo registrar sueños: tu diario onírico', duration: '12 min', type: 'lesson', module: 3 },
      { id: 'su-l8', title: 'Técnicas de recuerdo: capturar antes de que se vayan', duration: '14 min', type: 'lesson', module: 3 },
      { id: 'su-l9', title: 'Práctica: inicia tu diario de 30 días', duration: '10 min', type: 'lesson', module: 3 },
      { id: 'su-q3', title: 'Quiz: Técnicas de registro', duration: '5 min', type: 'quiz', module: 3 },
      { id: 'su-l10', title: 'Método de interpretación junguiana paso a paso', duration: '22 min', type: 'lesson', module: 4 },
      { id: 'su-l11', title: 'Amplificación: conectar con mitos y cultura', duration: '16 min', type: 'lesson', module: 4 },
      { id: 'su-l12', title: 'Práctica: interpreta 3 sueños reales', duration: '20 min', type: 'lesson', module: 4 },
      { id: 'su-q4', title: 'Quiz: Método de interpretación', duration: '5 min', type: 'quiz', module: 4 },
      { id: 'su-l13', title: 'Sueños recurrentes: el mensaje que insiste', duration: '15 min', type: 'lesson', module: 5 },
      { id: 'su-l14', title: 'Pesadillas: qué quiere decirte el miedo', duration: '16 min', type: 'lesson', module: 5 },
      { id: 'su-l15', title: 'Sueños lúcidos: cuando sabes que sueñas', duration: '18 min', type: 'lesson', module: 5 },
      { id: 'su-q5', title: 'Quiz: Tipos especiales de sueños', duration: '5 min', type: 'quiz', module: 5 },
      { id: 'su-l16', title: 'Sueños y carta natal: tu Luna como guía onírica', duration: '18 min', type: 'lesson', module: 6 },
      { id: 'su-l17', title: 'Neptuno y Casa 12: las puertas del inconsciente', duration: '16 min', type: 'lesson', module: 6 },
      { id: 'su-l18', title: 'Tránsitos y sueños: cuando el cielo habla de noche', duration: '14 min', type: 'lesson', module: 6 },
      { id: 'su-q6', title: 'Quiz: Astrología y sueños', duration: '5 min', type: 'quiz', module: 6 },
      { id: 'su-l19', title: 'Interpretación profesional: estructura de una sesión', duration: '18 min', type: 'lesson', module: 7 },
      { id: 'su-l20', title: 'Ética: límites, confidencialidad, derivación', duration: '12 min', type: 'lesson', module: 7 },
      { id: 'su-l21', title: 'Práctica: interpreta el sueño de otra persona', duration: '20 min', type: 'lesson', module: 7 },
      { id: 'su-q7', title: 'Quiz: Práctica profesional', duration: '5 min', type: 'quiz', module: 7 },
      { id: 'su-l22', title: 'Tu método personal de interpretación', duration: '15 min', type: 'lesson', module: 8 },
      { id: 'su-l23', title: 'Portfolio: tus mejores interpretaciones', duration: '12 min', type: 'lesson', module: 8 },
      { id: 'su-l24', title: 'Recursos, comunidad y próximos pasos', duration: '10 min', type: 'lesson', module: 8 },
      { id: 'su-exam', title: 'Evaluación final + Certificado', duration: '15 min', type: 'exam', module: 8 },
    ],
  },
  {
    id: 'quirologia-certificacion',
    title: 'Certificación en Quirología',
    subtitle: 'La única certificación en español — dermatoglifos, líneas y montes con base científica',
    level: 'Nivel 2',
    hours: '23h',
    modules: 8,
    lessons_count: 24,
    price: 4999,
    price_label: '€49,99',
    stripe_price_id: 'price_1TEqZd3w6LxSJCcMSPb8D3sk',
    icon: '🤚',
    color: COLORS.teal,
    tag: '🎓 Certificación',
    certification: true,
    cert_requirements: '7 quizzes aprobados + examen final (≥70%) + 10 manos fotografiadas y analizadas',
    cert_badge: 'Quirólogo/a Certificado/a Selene',
    cert_directory: true,
    science: 'Dermatoglifos (Cummins & Midlo 1943), correlación huellas-MBTI (Cureus 2022), biomarcadores de salud mental (ScienceDirect 2022), ratio 2D:4D (Manning 2002).',
    description: 'La ÚNICA certificación en quirología en español con base científica. 3 ramas integradas: quirognomía (forma), quiromancia (líneas) y dermatoglifos (crestas). Con diagramas interactivos y 6.000+ publicaciones científicas como respaldo.',
    for_whom: 'Quienes quieren ofrecer lecturas de manos profesionales con un enfoque que ningún competidor en español ofrece.',
    outcome: 'Clasificas manos en < 30 seg, lees líneas y montes con datación temporal, analizas dermatoglifos, y sabes cobrar €30-80/sesión.',
    lessons: [
      { id: 'qi-l1', title: 'Las 3 ramas de la quirología', duration: '40 min', type: 'lesson', module: 1 },
      { id: 'qi-l2', title: 'Historia: de Aristóteles a la ciencia moderna', duration: '35 min', type: 'lesson', module: 1 },
      { id: 'qi-l3', title: 'Preparar la lectura: luz, posición, ambas manos', duration: '35 min', type: 'lesson', module: 1 },
      { id: 'qi-q1', title: 'Quiz: Fundamentos', duration: '8 min', type: 'quiz', module: 1 },
      { id: 'qi-l4', title: 'Las 4 formas: tierra, fuego, agua, aire', duration: '40 min', type: 'lesson', module: 2 },
      { id: 'qi-l5', title: 'Análisis de dedos: longitud, falanges, flexibilidad', duration: '40 min', type: 'lesson', module: 2 },
      { id: 'qi-l6', title: 'El pulgar y las uñas: voluntad, lógica, salud', duration: '35 min', type: 'lesson', module: 2 },
      { id: 'qi-q2', title: 'Quiz: Quirognomía', duration: '8 min', type: 'quiz', module: 2 },
      { id: 'qi-l7', title: 'Línea de la vida: vitalidad y datación temporal', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'qi-l8', title: 'Línea del corazón: emociones y estilo afectivo', duration: '40 min', type: 'lesson', module: 3 },
      { id: 'qi-l9', title: 'Línea de la cabeza + línea del destino', duration: '40 min', type: 'lesson', module: 3 },
      { id: 'qi-q3', title: 'Quiz: Líneas mayores', duration: '8 min', type: 'quiz', module: 3 },
      { id: 'qi-l10', title: 'Los 7 montes planetarios', duration: '45 min', type: 'lesson', module: 4 },
      { id: 'qi-l11', title: 'Palpación: firmeza, prominencia, comparativa', duration: '35 min', type: 'lesson', module: 4 },
      { id: 'qi-l12', title: 'Combinaciones entre montes: lectura integrada', duration: '40 min', type: 'lesson', module: 4 },
      { id: 'qi-q4', title: 'Quiz: Montes', duration: '8 min', type: 'quiz', module: 4 },
      { id: 'qi-l13', title: 'Líneas secundarias: Marte, intuición, matrimonio', duration: '40 min', type: 'lesson', module: 5 },
      { id: 'qi-l14', title: 'Marcas especiales: estrellas, cruces, triángulos', duration: '40 min', type: 'lesson', module: 5 },
      { id: 'qi-l15', title: 'Formaciones raras: Simian, Sydney, Suwon', duration: '35 min', type: 'lesson', module: 5 },
      { id: 'qi-q5', title: 'Quiz: Líneas menores y marcas', duration: '8 min', type: 'quiz', module: 5 },
      { id: 'qi-l16', title: 'Base científica: de Cummins & Midlo a la neurociencia', duration: '40 min', type: 'lesson', module: 6 },
      { id: 'qi-l17', title: 'Los 3 patrones: arcos, bucles, verticilos', duration: '40 min', type: 'lesson', module: 6 },
      { id: 'qi-l18', title: 'Conteo de crestas y tu perfil dermatoglífico', duration: '35 min', type: 'lesson', module: 6 },
      { id: 'qi-q6', title: 'Quiz: Dermatoglifos', duration: '8 min', type: 'quiz', module: 6 },
      { id: 'qi-l19', title: 'El protocolo de 6 pasos', duration: '40 min', type: 'lesson', module: 7 },
      { id: 'qi-l20', title: 'Ambas manos: innato vs. adquirido + datación', duration: '40 min', type: 'lesson', module: 7 },
      { id: 'qi-l21', title: 'Ética, límites y comunicación empática', duration: '35 min', type: 'lesson', module: 7 },
      { id: 'qi-q7', title: 'Quiz: Lectura integrada', duration: '8 min', type: 'quiz', module: 7 },
      { id: 'qi-l22', title: 'Estructura de sesión profesional', duration: '35 min', type: 'lesson', module: 8 },
      { id: 'qi-l23', title: 'Lectura remota por foto: técnica y limitaciones', duration: '35 min', type: 'lesson', module: 8 },
      { id: 'qi-l24', title: 'Tu negocio: pricing, presencia online, certificación', duration: '35 min', type: 'lesson', module: 8 },
      { id: 'qi-exam', title: 'Evaluación final + Certificado', duration: '25 min', type: 'exam', module: 8 },
    ],
  },
  {
    id: 'guia-profesional',
    title: 'Máster en Guía Espiritual Profesional',
    subtitle: 'Convierte tu don en tu profesión — marca personal, ética y prácticas supervisadas',
    level: 'Nivel 3',
    hours: '40h',
    modules: 10,
    lessons_count: 30,
    price: 14999,
    price_label: '€149,99',
    stripe_price_id: 'price_1TEqZr3w6LxSJCcMKwkgKzNB',
    icon: '🌀',
    color: COLORS.gold,
    tag: '👑 Máster',
    certification: true,
    cert_requirements: 'Mínimo 2 certificaciones previas + 10 módulos + 10 consultas supervisadas + proyecto final de marca personal',
    cert_badge: 'Guía Profesional Certificada Selene',
    cert_directory: true,
    cert_prerequisite: 2,
    science: 'Integración de todos los pilares + ética profesional (ISAR/NCGR) + comunicación transformadora + emprendimiento digital.',
    description: 'El programa más completo. Has desarrollado tu don — ahora aprende a compartirlo profesionalmente. Incluye marca personal, ética, 10+ consultas supervisadas, y tu perfil premium en el directorio Selene.',
    for_whom: 'Quienes han completado 2+ certificaciones Selene y quieren ejercer profesionalmente. El paso definitivo hacia tu carrera como guía.',
    outcome: 'Marca personal lista, oferta de servicios definida, 10+ consultas supervisadas, código ético propio, y perfil premium en directorio Selene.',
    lessons: [
      // Module 1: El Método Selene
      { id: 'gp-l1', title: 'Qué es el Método Selene', duration: '45 min', type: 'lesson', module: 1 },
      { id: 'gp-l2', title: 'Tu perfil como guía: fortalezas y estilo', duration: '40 min', type: 'lesson', module: 1 },
      { id: 'gp-l3', title: 'Ética profesional: código de conducta', duration: '45 min', type: 'lesson', module: 1 },
      { id: 'gp-q1', title: 'Evaluación Módulo 1', duration: '15 min', type: 'quiz', module: 1 },
      // Module 2: Integración de disciplinas
      { id: 'gp-l4', title: 'Combinar astrología + tarot', duration: '45 min', type: 'lesson', module: 2 },
      { id: 'gp-l5', title: 'Combinar astrología + sueños + constelaciones', duration: '45 min', type: 'lesson', module: 2 },
      { id: 'gp-l6', title: 'Tu toolkit personalizado', duration: '40 min', type: 'lesson', module: 2 },
      { id: 'gp-q2', title: 'Evaluación Módulo 2', duration: '15 min', type: 'quiz', module: 2 },
      // Module 3: Psicología para guías
      { id: 'gp-l7', title: 'Escucha activa: Carl Rogers en la práctica', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'gp-l8', title: 'Transferencia y límites profesionales', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'gp-l9', title: 'Cuándo derivar: salud mental y crisis', duration: '45 min', type: 'lesson', module: 3 },
      { id: 'gp-q3', title: 'Evaluación Módulo 3', duration: '15 min', type: 'quiz', module: 3 },
      // Module 4: La sesión profesional
      { id: 'gp-l10', title: 'Estructura de sesión profesional', duration: '45 min', type: 'lesson', module: 4 },
      { id: 'gp-l11', title: 'Preguntas poderosas: facilitar sin dirigir', duration: '40 min', type: 'lesson', module: 4 },
      { id: 'gp-l12', title: 'Gestión emocional: llanto, silencio, resistencia', duration: '45 min', type: 'lesson', module: 4 },
      // Module 5: Casos prácticos
      { id: 'gp-l13', title: 'Caso 1: Primera consulta', duration: '50 min', type: 'lesson', module: 5 },
      { id: 'gp-l14', title: 'Caso 2: Consulta de pareja', duration: '50 min', type: 'lesson', module: 5 },
      { id: 'gp-l15', title: 'Caso 3: Crisis existencial', duration: '50 min', type: 'lesson', module: 5 },
      { id: 'gp-q5', title: 'Evaluación Módulos 4-5', duration: '20 min', type: 'quiz', module: 5 },
      // Module 6: Tu marca personal
      { id: 'gp-l16', title: 'Posicionamiento: nicho y diferencial', duration: '40 min', type: 'lesson', module: 6 },
      { id: 'gp-l17', title: 'Presencia online: web y redes', duration: '40 min', type: 'lesson', module: 6 },
      { id: 'gp-l18', title: 'Testimonios y portfolio', duration: '35 min', type: 'lesson', module: 6 },
      { id: 'gp-q6', title: 'Evaluación Módulo 6', duration: '15 min', type: 'quiz', module: 6 },
      // Module 7: Modelo de negocio
      { id: 'gp-l19', title: 'Pricing: cuánto cobrar (datos reales)', duration: '45 min', type: 'lesson', module: 7 },
      { id: 'gp-l20', title: 'Formatos: 1:1, grupales, talleres, retiros', duration: '45 min', type: 'lesson', module: 7 },
      { id: 'gp-l21', title: 'Herramientas: agenda, pagos, CRM', duration: '40 min', type: 'lesson', module: 7 },
      { id: 'gp-q7', title: 'Evaluación Módulo 7', duration: '15 min', type: 'quiz', module: 7 },
      // Module 8: Marketing y captación
      { id: 'gp-l22', title: 'Pinterest + Instagram: atraer sin vender', duration: '40 min', type: 'lesson', module: 8 },
      { id: 'gp-l23', title: 'Email marketing: tu lista es tu activo', duration: '40 min', type: 'lesson', module: 8 },
      { id: 'gp-l24', title: 'Referidos y boca a boca', duration: '35 min', type: 'lesson', module: 8 },
      // Module 9: Legalidad
      { id: 'gp-l25', title: 'Alta como profesional: España y Latam', duration: '45 min', type: 'lesson', module: 9 },
      { id: 'gp-l26', title: 'Facturación, impuestos y contabilidad', duration: '40 min', type: 'lesson', module: 9 },
      { id: 'gp-l27', title: 'RGPD y protección de datos', duration: '40 min', type: 'lesson', module: 9 },
      { id: 'gp-q9', title: 'Evaluación Módulos 8-9', duration: '20 min', type: 'quiz', module: 9 },
      // Module 10: Plan de lanzamiento
      { id: 'gp-l28', title: 'Tu plan de 90 días', duration: '45 min', type: 'lesson', module: 10 },
      { id: 'gp-l29', title: 'Las 30 lecturas gratuitas: tu rito de paso', duration: '40 min', type: 'lesson', module: 10 },
      { id: 'gp-l30', title: 'Mentoría continua y crecimiento', duration: '40 min', type: 'lesson', module: 10 },
      { id: 'gp-exam', title: 'Evaluación final + Proyecto de marca + Certificado Máster', duration: '60 min', type: 'exam', module: 10 },
    ],
  },
];

// ── Levels ──
export const LEVELS = [
  { name: 'Semilla Cósmica', minXp: 0, maxXp: 500 },
  { name: 'Exploración Cósmica', minXp: 500, maxXp: 2000 },
  { name: 'Navegante Estelar', minXp: 2000, maxXp: 5000 },
  { name: 'Guardián Lunar', minXp: 5000, maxXp: 10000 },
  { name: 'Luz Maestra', minXp: 10000, maxXp: Infinity },
];

export function getLevel(xp) {
  return LEVELS.find(l => xp >= l.minXp && xp < l.maxXp) || LEVELS[0];
}

// ── XP Rewards ──
export const XP_REWARDS = {
  lesson_complete: 50,
  quiz_pass: 100,
  exam_pass: 250,
  streak_day: 25,
  course_complete: 500,
};

// ── Quiz Questions ──
// Keyed by lesson ID. Each quiz/exam has at least 3 questions.
export const QUIZ_QUESTIONS = {
  // Module 1: Fundamentos de consciencia
  'b1-q1': [
    {
      q: '¿Qué significa "espiritualidad consciente" en el contexto de este curso?',
      options: ['Seguir dogmas religiosos', 'Atención entrenada basada en evidencia', 'Creencia ciega en lo sobrenatural', 'Prácticas sin base científica'],
      correct: 1,
    },
    {
      q: '¿Qué propiedad del cerebro permite que la meditación modifique sus estructuras?',
      options: ['La memoria a largo plazo', 'La neuroplasticidad', 'El efecto placebo', 'La herencia genética'],
      correct: 1,
    },
    {
      q: '¿Cuál es la diferencia entre fe ciega y atención entrenada?',
      options: ['No hay diferencia', 'La atención entrenada se basa en práctica repetida y observable', 'La fe ciega es más efectiva', 'La atención entrenada requiere religión'],
      correct: 1,
    },
  ],
  // Module 2: Tu mapa cósmico
  'b1-q2': [
    {
      q: '¿Qué representa el "triángulo" Sol-Luna-Ascendente en astrología?',
      options: ['Tres planetas del sistema solar', 'Los tres aspectos fundamentales de tu personalidad', 'Tres fases de la luna', 'Tres constelaciones'],
      correct: 1,
    },
    {
      q: '¿Qué estudia la cronobiología?',
      options: ['Los horóscopos diarios', 'Los ritmos biológicos y su sincronización', 'La astrología natal', 'Las fases lunares exclusivamente'],
      correct: 1,
    },
    {
      q: '¿Qué es una carta natal?',
      options: ['Un horóscopo del periódico', 'Un mapa de las posiciones planetarias en el momento de tu nacimiento', 'Una lectura de tarot', 'Un test de personalidad'],
      correct: 1,
    },
  ],
  // Module 3: Meditación basada en evidencia
  'b1-q3': [
    {
      q: '¿Qué estructura cerebral se modifica con la práctica meditativa según los estudios de neuroplasticidad?',
      options: ['El hipocampo', 'La corteza prefrontal', 'La amígdala', 'Todas las anteriores'],
      correct: 3,
    },
    {
      q: '¿Qué protocolo tiene la mayor base de evidencia peer-reviewed para meditación?',
      options: ['Visualización creativa', 'MBSR (Mindfulness-Based Stress Reduction)', 'Meditación trascendental', 'Yoga nidra'],
      correct: 1,
    },
    {
      q: '¿Quién desarrolló el protocolo MBSR?',
      options: ['Deepak Chopra', 'Jon Kabat-Zinn', 'Matthieu Ricard', 'Thich Nhat Hanh'],
      correct: 1,
    },
  ],
  // Module 4: Intuición entrenada
  'b1-q4': [
    {
      q: '¿Qué es el eje intestino-cerebro?',
      options: ['Un ejercicio de yoga', 'La conexión bidireccional entre el sistema digestivo y el cerebro', 'Una dieta especial', 'Un tipo de meditación'],
      correct: 1,
    },
    {
      q: '¿Cuál es la diferencia entre intuición y ego según este módulo?',
      options: ['Son lo mismo', 'La intuición es serena y el ego genera urgencia/miedo', 'El ego es siempre correcto', 'La intuición no existe científicamente'],
      correct: 1,
    },
    {
      q: '¿Cómo se entrena la intuición según la evidencia presentada?',
      options: ['Leyendo horóscopos', 'Con práctica repetida de escucha corporal y atención plena', 'Con suplementos', 'No se puede entrenar'],
      correct: 1,
    },
  ],
  // Module 5: Autoconocimiento
  'b1-q5': [
    {
      q: '¿Cuáles son los 4 pilares del autoconocimiento presentados en el curso?',
      options: ['Tarot, astrología, meditación, yoga', 'Cuerpo, mente, emociones, espíritu', 'Tierra, agua, fuego, aire', 'Sol, luna, estrellas, planetas'],
      correct: 1,
    },
    {
      q: '¿Qué es un "perfil energético"?',
      options: ['Tu consumo eléctrico', 'Un mapa de tus patrones de energía personal basado en observación', 'Un análisis de sangre', 'Tu signo zodiacal'],
      correct: 1,
    },
    {
      q: '¿Por qué es importante el mapa de energía personal?',
      options: ['Para predecir el futuro', 'Para identificar patrones y optimizar tu bienestar diario', 'Para impresionar a otros', 'No tiene utilidad real'],
      correct: 1,
    },
  ],
  // ── Raíces Invisibles (Constelaciones + Astrogenealogía) ──
  // Module 1: Fundamentos sistémicos
  'ri-q1': [
    {
      q: '¿Cuál es la premisa central de la Teoría de Sistemas Familiares de Bowen?',
      options: ['Cada persona es independiente de su familia', 'La familia funciona como un sistema emocional interconectado', 'Solo importan los genes heredados', 'Los patrones familiares no se transmiten'],
      correct: 1,
    },
    {
      q: '¿Cuáles son las tres leyes sistémicas fundamentales?',
      options: ['Amor, verdad, justicia', 'Pertenencia, orden y equilibrio', 'Nacimiento, vida y muerte', 'Pasado, presente y futuro'],
      correct: 1,
    },
    {
      q: '¿Qué estudia la epigenética transgeneracional?',
      options: ['La secuencia del ADN', 'Cómo las experiencias de generaciones anteriores modifican la expresión genética en descendientes', 'Solo las enfermedades hereditarias', 'Las mutaciones genéticas al azar'],
      correct: 1,
    },
  ],
  // Module 2: Las casas familiares
  'ri-q2': [
    {
      q: '¿Qué representa la Casa 4 en la carta natal?',
      options: ['Las amistades', 'Las raíces, el hogar emocional y la familia de origen', 'La carrera profesional', 'Los viajes largos'],
      correct: 1,
    },
    {
      q: '¿Qué temas rige la Casa 8?',
      options: ['La comunicación', 'Herencias, transformación, secretos y recursos compartidos', 'El trabajo diario', 'La identidad personal'],
      correct: 1,
    },
    {
      q: '¿Por qué la Casa 12 se relaciona con el inconsciente familiar?',
      options: ['Es la última casa del zodíaco', 'Representa lo oculto, los patrones inconscientes y las memorias no procesadas del linaje', 'Solo habla de espiritualidad', 'No tiene relación con la familia'],
      correct: 1,
    },
  ],
  // Module 3: Planetas de herencia
  'ri-q3': [
    {
      q: '¿Qué herencia representa la Luna en la carta natal?',
      options: ['La herencia económica', 'La herencia emocional y los patrones maternos', 'La herencia intelectual', 'La herencia física'],
      correct: 1,
    },
    {
      q: '¿Qué función tiene Saturno en el sistema familiar?',
      options: ['Expansión y suerte', 'Estructura, límites, mandatos y responsabilidades heredadas', 'Creatividad y romance', 'Comunicación y viajes'],
      correct: 1,
    },
    {
      q: '¿Qué simbolizan los Nodos Lunares a nivel transgeneracional?',
      options: ['Las fases de la luna', 'El eje entre patrones heredados (Nodo Sur) y la evolución pendiente (Nodo Norte)', 'Los eclipses solamente', 'No tienen significado familiar'],
      correct: 1,
    },
  ],
  // Module 4: Herencia transgeneracional
  'ri-q4': [
    {
      q: '¿Qué demostró la investigación de Rachel Yehuda sobre descendientes del Holocausto?',
      options: ['Que el trauma no se transmite', 'Que los marcadores epigenéticos del trauma se encontraron en la siguiente generación', 'Que solo afecta a quienes lo vivieron', 'Que el ADN no cambia nunca'],
      correct: 1,
    },
    {
      q: '¿Qué son las "lealtades invisibles"?',
      options: ['Contratos legales familiares', 'Vínculos inconscientes que nos llevan a repetir patrones familiares por fidelidad al sistema', 'Promesas hechas en voz alta', 'Tradiciones culturales elegidas'],
      correct: 1,
    },
    {
      q: '¿Qué es un genograma emocional?',
      options: ['Un test de ADN', 'Un mapa visual de las relaciones y patrones emocionales de al menos 3 generaciones familiares', 'Un horóscopo familiar', 'Una lista de antepasados'],
      correct: 1,
    },
  ],
  // Module 5: Astrogenealogía aplicada
  'ri-q5': [
    {
      q: '¿Qué es la astrogenealogía?',
      options: ['Una rama de la astronomía', 'La disciplina que estudia cómo la carta natal refleja dinámicas del sistema familiar', 'Un tipo de tarot', 'Una pseudociencia sin aplicación'],
      correct: 1,
    },
    {
      q: '¿Qué aspecto planetario podría indicar conflictos familiares no resueltos?',
      options: ['Trígonos al Sol', 'Cuadraturas de Saturno o Plutón a la Luna o al IC', 'Conjunciones Venus-Júpiter', 'Sextiles a Mercurio'],
      correct: 1,
    },
    {
      q: '¿Por qué suelen repetirse temas astrológicos dentro de una misma familia?',
      options: ['Es pura casualidad', 'Porque los patrones sistémicos se reflejan en configuraciones planetarias compartidas entre miembros', 'Porque todos nacen el mismo día', 'No se repiten'],
      correct: 1,
    },
  ],
  // Module 6: Transformación sistémica
  'ri-q6': [
    {
      q: '¿Qué son los "movimientos sistémicos" individuales?',
      options: ['Ejercicios físicos', 'Ejercicios de visualización guiada donde representas a miembros de tu sistema familiar para revelar dinámicas', 'Mudanzas de casa', 'Técnicas de respiración'],
      correct: 1,
    },
    {
      q: '¿Cuál es el objetivo de honrar el linaje en el trabajo sistémico?',
      options: ['Idealizar a los antepasados', 'Reconocer que cada miembro del sistema tiene un lugar, lo que permite liberar lealtades inconscientes', 'Repetir sus errores', 'Olvidar el pasado'],
      correct: 1,
    },
    {
      q: '¿Para qué sirve la "carta de liberación" al sistema familiar?',
      options: ['Para romper lazos con la familia', 'Para expresar conscientemente lo no dicho, honrar lo vivido y soltar mandatos que ya no te sirven', 'Para quejarse', 'No tiene ningún propósito terapéutico'],
      correct: 1,
    },
  ],
  // Module 7: Relaciones y sistema
  'ri-q7': [
    {
      q: '¿Cómo influyen los patrones familiares en la elección de pareja?',
      options: ['No influyen en absoluto', 'Tendemos a elegir personas que activan dinámicas familiares no resueltas, como espejo inconsciente', 'Solo influye el aspecto físico', 'Es puro azar'],
      correct: 1,
    },
    {
      q: '¿Qué es la "sinastría sistémica"?',
      options: ['Comparar signos solares', 'Analizar cómo los patrones familiares de ambas personas interactúan a través de la comparación de cartas natales', 'Leer el tarot en pareja', 'Un tipo de terapia de grupo'],
      correct: 1,
    },
    {
      q: '¿Qué significa "romper el ciclo" en el contexto sistémico?',
      options: ['Cortar relación con la familia', 'Tomar consciencia de los patrones heredados y elegir activamente respuestas diferentes', 'Ignorar el pasado', 'Cambiar de nombre'],
      correct: 1,
    },
  ],
  // Module 8: Evaluación final Raíces Invisibles
  'ri-exam': [
    {
      q: '¿Qué tres casas de la carta natal se asocian con patrones familiares?',
      options: ['Casas 1, 5 y 9', 'Casas 4, 8 y 12', 'Casas 2, 6 y 10', 'Casas 3, 7 y 11'],
      correct: 1,
    },
    {
      q: '¿Qué evidencia científica respalda la transmisión transgeneracional del trauma?',
      options: ['Ninguna', 'Estudios de epigenética (Yehuda 2016) y la Teoría de Sistemas de Bowen', 'Solo estudios de astrología', 'Solo la tradición oral'],
      correct: 1,
    },
    {
      q: '¿Qué planeta representa los mandatos y limitaciones heredadas del sistema familiar?',
      options: ['Júpiter', 'Venus', 'Saturno', 'Marte'],
      correct: 2,
    },
    {
      q: '¿Qué son las lealtades invisibles?',
      options: ['Promesas conscientes', 'Vínculos inconscientes que nos llevan a repetir patrones por fidelidad al sistema familiar', 'Contratos familiares escritos', 'Herencias económicas'],
      correct: 1,
    },
    {
      q: '¿Cuál es el objetivo final del trabajo de astrogenealogía?',
      options: ['Culpar a la familia', 'Identificar patrones heredados, honrar el sistema y elegir conscientemente tu propio camino', 'Predecir el futuro familiar', 'Cortar lazos familiares'],
      correct: 1,
    },
  ],
  // ── Brújula Interior ──
  // Module 6: Evaluación final
  'b1-exam': [
    {
      q: '¿Qué estructura cerebral se modifica con la práctica meditativa según los estudios de neuroplasticidad?',
      options: ['El hipocampo', 'La corteza prefrontal', 'La amígdala', 'Todas las anteriores'],
      correct: 3,
    },
    {
      q: '¿Qué protocolo tiene la mayor base de evidencia peer-reviewed para meditación?',
      options: ['Visualización creativa', 'MBSR (Mindfulness-Based Stress Reduction)', 'Meditación trascendental', 'Yoga nidra'],
      correct: 1,
    },
    {
      q: 'La cronobiología estudia:',
      options: ['Los horóscopos diarios', 'Los ritmos biológicos y su sincronización', 'La astrología natal', 'Las fases lunares exclusivamente'],
      correct: 1,
    },
    {
      q: '¿Qué es el eje intestino-cerebro?',
      options: ['Un ejercicio de yoga', 'La conexión bidireccional entre el sistema digestivo y el cerebro', 'Una dieta especial', 'Un tipo de meditación'],
      correct: 1,
    },
    {
      q: '¿Qué representa el triángulo Sol-Luna-Ascendente?',
      options: ['Tres planetas lejanos', 'Los tres aspectos fundamentales de tu personalidad', 'Tres fases de la luna', 'Tres tipos de meditación'],
      correct: 1,
    },
  ],
};
