// ═══════════════════════════════════════════════
// SELENE ACADEMIA — Constants & Data
// ═══════════════════════════════════════════════

// ── Design Tokens (complement Tailwind) ──
export const COLORS = {
  gold: '#C9A84C',
  teal: '#5B9E8F',
  blue: '#4A6FA5',
  purple: '#7B68AE',
  rose: '#C97B8B',
  success: '#5BB88F',
};

// ── Course Catalog ──
export const COURSES = [
  {
    id: 'brujula-interior',
    title: 'Despierta tu Brújula Interior',
    subtitle: 'Fundamentos de consciencia espiritual y autoconocimiento cósmico',
    level: 'Nivel 0',
    hours: '12h',
    modules: 6,
    lessons_count: 24,
    price: 0,
    price_label: 'GRATIS',
    stripe_price_id: null,
    icon: '🌟',
    color: COLORS.teal,
    tag: 'Lead Magnet',
    science: 'Neuroplasticidad (MBSR — Kabat-Zinn 1990), cronobiología introductoria, eje intestino-cerebro (Mayer 2011).',
    description: 'El punto de partida. Descubre que tienes un don dormido y aprende a despertarlo. Tu carta natal básica, tu primera meditación con resultados reales, y la hoja de ruta para tu camino formativo.',
    for_whom: 'Curiosos, escépticos, personas que sienten que "hay algo más" pero no saben por dónde empezar.',
    outcome: 'Entiendes tu carta natal básica, has hecho tu primera meditación con resultados, y sabes qué camino formativo seguir.',
    lessons: [
      { id: 'b1-l1', title: '¿Qué es la espiritualidad consciente?', duration: '18 min', type: 'video', module: 1 },
      { id: 'b1-l2', title: 'No es fe ciega: es atención entrenada', duration: '12 min', type: 'video', module: 1 },
      { id: 'b1-l3', title: 'Tu cerebro como antena: neuroplasticidad', duration: '15 min', type: 'video', module: 1 },
      { id: 'b1-q1', title: 'Quiz: Fundamentos de consciencia', duration: '5 min', type: 'quiz', module: 1 },
      { id: 'b1-l4', title: 'Tu mapa cósmico — La carta natal', duration: '22 min', type: 'video', module: 2 },
      { id: 'b1-l5', title: 'Sol, Luna, Ascendente: tu triángulo', duration: '18 min', type: 'video', module: 2 },
      { id: 'b1-l6', title: 'Cronobiología: tu estación de nacimiento importa', duration: '14 min', type: 'video', module: 2 },
      { id: 'b1-q2', title: 'Quiz: Tu mapa cósmico', duration: '5 min', type: 'quiz', module: 2 },
      { id: 'b1-l7', title: 'Meditación y cerebro: la ciencia real', duration: '20 min', type: 'video', module: 3 },
      { id: 'b1-l8', title: 'MBSR: el protocolo con más evidencia', duration: '16 min', type: 'video', module: 3 },
      { id: 'b1-l9', title: 'Práctica guiada: tu primera meditación', duration: '15 min', type: 'video', module: 3 },
      { id: 'b1-q3', title: 'Quiz: Meditación basada en evidencia', duration: '5 min', type: 'quiz', module: 3 },
      { id: 'b1-l10', title: 'El péndulo interno: intuición vs. ego', duration: '15 min', type: 'video', module: 4 },
      { id: 'b1-l11', title: 'Señales del cuerpo: el eje intestino-cerebro', duration: '14 min', type: 'video', module: 4 },
      { id: 'b1-l12', title: 'Práctica: escucha tu intuición 7 días', duration: '10 min', type: 'video', module: 4 },
      { id: 'b1-q4', title: 'Quiz: Intuición entrenada', duration: '5 min', type: 'quiz', module: 4 },
      { id: 'b1-l13', title: 'Los 4 pilares del autoconocimiento', duration: '18 min', type: 'video', module: 5 },
      { id: 'b1-l14', title: 'Tu perfil energético: descúbrelo', duration: '20 min', type: 'video', module: 5 },
      { id: 'b1-l15', title: 'Práctica: mapa de energía personal', duration: '12 min', type: 'video', module: 5 },
      { id: 'b1-q5', title: 'Quiz: Autoconocimiento', duration: '5 min', type: 'quiz', module: 5 },
      { id: 'b1-l16', title: 'Tu hoja de ruta formativa', duration: '15 min', type: 'video', module: 6 },
      { id: 'b1-l17', title: 'Resumen: lo que has aprendido', duration: '10 min', type: 'video', module: 6 },
      { id: 'b1-l18', title: 'Recursos y próximos pasos', duration: '8 min', type: 'video', module: 6 },
      { id: 'b1-exam', title: 'Evaluación final + Certificado', duration: '15 min', type: 'exam', module: 6 },
    ],
  },
  {
    id: 'magnetismo-consciente',
    title: 'Magnetismo Consciente',
    subtitle: 'Neurociencia de la atracción y la intención — lo que la ley de atracción no te cuenta',
    level: 'Nivel 1',
    hours: '18h',
    modules: 8,
    lessons_count: 24,
    price: 2499,
    price_label: '€24,99',
    stripe_price_id: null, // Set in env: STRIPE_PRICE_MAGNETISMO
    icon: '🧲',
    color: COLORS.purple,
    tag: 'Popular',
    science: 'HeartMath Institute (McCraty 2015), neuroplasticidad (Lazar 2005), epigenética conductual (Meaney 2001), sistema de activación reticular.',
    description: 'La "ley de atracción" con base científica real. Coherencia cardíaca, rewiring neuronal, y cómo tus genes responden a tus estados emocionales.',
    for_whom: 'Personas interesadas en manifestación que quieren entender QUÉ funciona y POR QUÉ, sin pseudociencia.',
    outcome: 'Dominas la coherencia cardíaca HeartMath, entiendes la neuroplasticidad aplicada, y tienes una rutina de 21 días con base científica.',
    lessons: [],
  },
  {
    id: 'astrologia-natal',
    title: 'Astrología Natal Profunda',
    subtitle: 'Tu carta natal al detalle — planetas, casas, aspectos y tránsitos',
    level: 'Nivel 1',
    hours: '22h',
    modules: 10,
    lessons_count: 30,
    price: 2999,
    price_label: '€29,99',
    stripe_price_id: null,
    icon: '🌙',
    color: COLORS.blue,
    tag: 'Nuevo',
    science: 'Astronomía posicional (efemérides JPL), cronobiología (Foster & Kreitzman 2017), psicología junguiana (arquetipos).',
    description: 'De saber tu signo solar a interpretar una carta natal completa. Planetas personales, casas, aspectos, y cómo leer los tránsitos actuales.',
    for_whom: 'Quienes quieren ir más allá del horóscopo del periódico y entender la astrología como sistema simbólico complejo.',
    outcome: 'Interpretas tu carta natal completa, identificas tus tránsitos activos, y puedes hacer una lectura básica para otros.',
    lessons: [],
  },
  {
    id: 'cronobiologia',
    title: 'Cronobiología y Ritmos Vitales',
    subtitle: 'La ciencia real de cómo los ciclos cósmicos afectan tu biología',
    level: 'Nivel 2',
    hours: '20h',
    modules: 8,
    lessons_count: 24,
    price: 2999,
    price_label: '€29,99',
    stripe_price_id: null,
    icon: '🧬',
    color: COLORS.teal,
    tag: 'Ciencia',
    science: 'Ritmos circadianos (Nobel 2017 — Hall, Rosbash, Young), genes PER1/CLOCK, melatonina, cortisol, serotonina, estudios Gonda 2014, Current Biology 2013/2021.',
    description: 'El curso más "científico" de Selene. Donde la astrología encuentra la biología molecular. Ritmos circadianos, ultradianos, lunares y estacionales con evidencia real.',
    for_whom: 'Escépticos curiosos, profesionales de salud/bienestar, y cualquiera que quiera entender la base real.',
    outcome: 'Entiendes cómo los ritmos biológicos afectan tu vida diaria y diseñas tu calendario personalizado en sincronía.',
    lessons: [],
  },
  {
    id: 'tarot-intuitivo',
    title: 'El Arte del Tarot Intuitivo',
    subtitle: 'De las cartas como adivinación a herramienta de transformación interior',
    level: 'Nivel 2',
    hours: '25h',
    modules: 10,
    lessons_count: 30,
    price: 3499,
    price_label: '€34,99',
    stripe_price_id: null,
    icon: '✨',
    color: COLORS.gold,
    tag: 'Certificación',
    science: 'Psicología proyectiva (Jung 1964), arquetipos del inconsciente colectivo, intuición como sistema neurológico (Kahneman 2011).',
    description: 'Olvida memorizar significados. Aprende a SENTIR las cartas. El tarot es un espejo del inconsciente, no una bola de cristal.',
    for_whom: 'Interesados en tarot que quieren ir más allá de "qué significa esta carta". Enfoque terapéutico y proyectivo.',
    outcome: 'Haces tiradas intuitivas de 30+ min con narrativa coherente, integras tarot + astrología, y puedes ofrecer lecturas.',
    lessons: [],
  },
  {
    id: 'guia-profesional',
    title: 'Guía Espiritual Profesional',
    subtitle: 'El Máster: convierte tu don en tu profesión',
    level: 'Nivel 3',
    hours: '40h',
    modules: 10,
    lessons_count: 30,
    price: 5999,
    price_label: '€59,99',
    stripe_price_id: null,
    icon: '🌀',
    color: COLORS.gold,
    tag: 'Máster',
    science: 'Integración de todos los pilares + ética profesional (ISAR/NCGR) + comunicación transformadora + emprendimiento.',
    description: 'Has desarrollado tu don. Ahora aprende a compartirlo profesionalmente, éticamente, y con éxito. Incluye prácticas supervisadas.',
    for_whom: 'Alumnos que han completado 3+ cursos Selene y quieren ejercer profesionalmente como guías espirituales.',
    outcome: 'Marca personal, oferta de servicios, 10+ consultas supervisadas, código ético, y perfil en directorio Selene.',
    lessons: [],
  },
];

// ── Levels ──
export const LEVELS = [
  { name: 'Semilla Cósmica', minXp: 0, maxXp: 500 },
  { name: 'Exploradora Cósmica', minXp: 500, maxXp: 2000 },
  { name: 'Navegante Estelar', minXp: 2000, maxXp: 5000 },
  { name: 'Guardiana Lunar', minXp: 5000, maxXp: 10000 },
  { name: 'Maestra de la Luz', minXp: 10000, maxXp: Infinity },
];

export function getLevel(xp) {
  return LEVELS.find(l => xp >= l.minXp && xp < l.maxXp) || LEVELS[0];
}

// ── XP Rewards ──
export const XP_REWARDS = {
  lesson_complete: 50,
  quiz_pass: 100,
  exam_pass: 250,
  streak_day: 25,
  course_complete: 500,
};
